[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.packager]
before-packaging-command = "cargo build --release"

[dependencies]
sysinfo = "0.30.11"
tungstenite = "0.21.0"